- name: Restart sshd on CentOS
  service:
    name: sshd
    state: restarted
  listen: restart_sshd
  when: ansible_distribution == "CentOS"

- name: Restart ssh on Ubuntu
  service:
    name: ssh
    state: restarted
  listen: restart_sshd
  when: ansible_distribution == "Ubuntu"