- name: add ssh key for admin1
  authorized_key:
    user: admin1
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGN1R3zh9GAnHQkpu1j8xggx+k38cjC+WtS2EejgF2EI ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd